name: Spellcheck
on: [push, pull_request]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: rojopolis/spellcheck-github-actions@0.21.1
      name: Spellcheck